spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.nineleaps.notification.model.UserDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.nineleaps.notification.model.UserSerializer
  data:
    cassandra:
      keyspace-name: nineleaps
      port: 9042
      contact-points: 127.0.0.1 
  main:
    allow-bean-definition-overriding: true